import type { BrandNode } from "@/lib/catalog/brand-hierarchy";

/**
 * Researched brand-hierarchy facts (verified-data research workflow, 2026-06-11).
 * Every sourceUrl was retrieved or seen verbatim in search results at research
 * time; relationships without a supporting source were not added.
 * GENERATED by scripts/ingest-research-results.mjs — do not hand-edit
 * relationships without a source.
 */
export const BRAND_HIERARCHY_ENTRIES: BrandNode[] = [
 {
  "brand": "Square D",
  "aliases": [
   "Square D by Schneider Electric"
  ],
  "division": "Flagship Schneider Electric brand for electrical distribution and industrial control (US)",
  "parentCompany": "Schneider Electric",
  "sourceUrl": "https://www.se.com/us/en/brands/squared/about/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Schneider Electric",
  "aliases": [
   "Schneider Electric SE"
  ],
  "parentCompany": "Schneider Electric",
  "sourceUrl": "https://www.se.com/ww/en/about-us/company-profile/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Eaton",
  "aliases": [
   "Eaton Corporation plc"
  ],
  "parentCompany": "Eaton",
  "sourceUrl": "https://www.eaton.com/us/en-us/company/about-us.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/e/eaton.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Eaton B-Line",
  "aliases": [
   "B-Line",
   "B-Line series",
   "Cooper B-Line",
   "Eaton's B-Line series"
  ],
  "division": "B-Line series (Eaton support systems / cable management portfolio; formerly Cooper B-Line)",
  "parentCompany": "Eaton",
  "sourceUrl": "https://www.eaton.com/us/en-us/products/support-systems.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/e/eaton/eaton-b-line-series.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Bussmann",
  "aliases": [
   "Bussmann series",
   "Eaton Bussmann Series",
   "Cooper Bussmann"
  ],
  "division": "Bussmann series (Eaton circuit protection, St. Louis, MO; formerly Cooper Bussmann)",
  "parentCompany": "Eaton",
  "sourceUrl": "https://www.eaton.com/us/en-us/products/electrical-circuit-protection/fuses.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/e/eaton/eaton-bussmann-series.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Tripp Lite",
  "aliases": [
   "Tripp Lite by Eaton"
  ],
  "division": "Eaton power quality business (Americas)",
  "parentCompany": "Eaton",
  "sourceUrl": "https://www.eaton.com/us/en-us/company/news-insights/news-releases/2021/eaton-completes-the-acquisition-of-tripp-lite--expanding-eaton-s.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "GE (ABB)",
  "aliases": [
   "GE",
   "GE Industrial Solutions",
   "GEIS"
  ],
  "division": "ABB Electrification (GE Industrial Solutions integrated as Electrification Products Industrial Solutions); GE brand used by ABB under a long-term right acquired in the deal",
  "parentCompany": "ABB",
  "sourceUrl": "https://new.abb.com/news/detail/5475/abb-completes-acquisition-of-ge-industrial-solutions",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "ABB",
  "aliases": [
   "ABB Ltd",
   "ABB Group"
  ],
  "parentCompany": "ABB",
  "sourceUrl": "https://www.abb.com/global/en/company/about",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/a/abb.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Thomas & Betts",
  "aliases": [
   "T&B",
   "ABB Installation Products"
  ],
  "division": "ABB Installation Products (formerly Thomas & Betts), within ABB's low-voltage/Electrification business",
  "parentCompany": "ABB",
  "sourceUrl": "https://new.abb.com/news/detail/13297/abb-completes-acquisition-of-thomas-betts",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/a/abb/abb-installation-products.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Siemens",
  "aliases": [
   "Siemens AG"
  ],
  "parentCompany": "Siemens",
  "sourceUrl": "https://www.siemens.com/global/en/company/about.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Allen-Bradley",
  "aliases": [
   "Allen Bradley",
   "A-B"
  ],
  "division": "Flagship product brand of Rockwell Automation (industrial automation hardware)",
  "parentCompany": "Rockwell Automation",
  "sourceUrl": "https://www.rockwellautomation.com/en-us/company.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Hubbell",
  "aliases": [
   "Hubbell Incorporated"
  ],
  "parentCompany": "Hubbell",
  "sourceUrl": "https://www.hubbell.com/hubbell/en",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/h/hubbell.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "RACO",
  "aliases": [
   "Hubbell-RACO"
  ],
  "division": "Hubbell Commercial Construction business",
  "parentCompany": "Hubbell",
  "sourceUrl": "https://www.hubbell.com/raco/en/about-us",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Burndy",
  "division": "Hubbell Electrical Systems",
  "parentCompany": "Hubbell",
  "sourceUrl": "https://www.hubbell.com/burndy/en/about-us",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "APC",
  "aliases": [
   "APC by Schneider Electric",
   "American Power Conversion"
  ],
  "division": "Flagship Schneider Electric brand for battery back-up/UPS and IT physical infrastructure (formerly American Power Conversion, acquired 2007)",
  "parentCompany": "Schneider Electric",
  "sourceUrl": "https://www.wesco.com/us/en/brands/a/apc-by-schneider-electric.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/a/apc-by-schneider-electric.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Leviton",
  "aliases": [
   "Leviton Manufacturing",
   "Leviton Electrical Solutions",
   "Leviton Network Solutions"
  ],
  "parentCompany": "Leviton Manufacturing Co., Inc. (independent, family-owned)",
  "sourceUrl": "https://leviton.com/company/about-leviton1",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/l/leviton.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Pass & Seymour",
  "aliases": [
   "Pass and Seymour"
  ],
  "division": "Legrand North America",
  "parentCompany": "Legrand",
  "sourceUrl": "https://www.legrand.us/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Legrand Cablofil",
  "aliases": [
   "Cablofil"
  ],
  "subBrand": "Cablofil",
  "division": "Legrand North America",
  "parentCompany": "Legrand",
  "sourceUrl": "https://www.legrand.us/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Wattstopper",
  "aliases": [
   "Legrand Wattstopper"
  ],
  "division": "Legrand North America",
  "parentCompany": "Legrand",
  "sourceUrl": "https://www.legrand.us/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Lutron",
  "aliases": [
   "Lutron Electronics",
   "Lutron Electronics Co"
  ],
  "parentCompany": "Lutron Electronics Co., Inc. (independent, privately held)",
  "sourceUrl": "https://www.lutron.com/us/en/about/who-we-are",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "3M",
  "aliases": [
   "3M Company"
  ],
  "parentCompany": "3M Company (independent; 3M is the ultimate parent)",
  "sourceUrl": "https://www.3m.com/3M/en_US/company-us/about-3m/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Panduit",
  "aliases": [
   "Panduit Corp"
  ],
  "parentCompany": "Panduit Corp. (independent, privately owned)",
  "sourceUrl": "https://www.panduit.com/en/about/company-profile.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/p/panduit.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Southwire",
  "parentCompany": "Southwire Company, LLC (independent, family-owned)",
  "sourceUrl": "https://www.southwire.com/family-owned",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/s/southwire.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Metalux",
  "division": "Cooper Lighting Solutions",
  "parentCompany": "Signify",
  "sourceUrl": "https://www.cooperlighting.com/global/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Halo",
  "aliases": [
   "HALO Commercial"
  ],
  "division": "Cooper Lighting Solutions",
  "parentCompany": "Signify",
  "sourceUrl": "https://www.cooperlighting.com/global/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Sure-Lites",
  "division": "Cooper Lighting Solutions",
  "parentCompany": "Signify",
  "sourceUrl": "https://www.cooperlighting.com/global/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Sylvania",
  "aliases": [
   "LEDVANCE SYLVANIA",
   "Osram Sylvania (historical labeling)"
  ],
  "division": "LEDVANCE LLC — SYLVANIA general lighting, US/Canada",
  "parentCompany": "MLS Co., Ltd. (via LEDVANCE)",
  "sourceUrl": "https://www.ledvance.com/en-us/company/about-ledvance/ledvance-sylvania-brand-story",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Philips Advance",
  "aliases": [
   "Advance"
  ],
  "subBrand": "Advance",
  "division": "Genlyte Solutions (Signify North America)",
  "parentCompany": "Signify",
  "sourceUrl": "https://www.genlyte.com/en-us/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Philips Day-Brite",
  "aliases": [
   "Day-Brite"
  ],
  "subBrand": "Day-Brite",
  "division": "Genlyte Solutions (Signify North America)",
  "parentCompany": "Signify",
  "sourceUrl": "https://www.genlyte.com/en-us/brands",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Columbia Lighting",
  "aliases": [
   "Columbia",
   "Hubbell Columbia Lighting (historical labeling)"
  ],
  "division": "HLI Brands (formerly Hubbell Lighting)",
  "parentCompany": "Current Lighting Solutions, LLC (portfolio company of American Industrial Partners)",
  "sourceUrl": "https://www.currentlighting.com/newsroom/ge-current-daintree-company-completes-acquisition-of-hubbell-commercial-industrial-lighting-to-create-current",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Cree Lighting",
  "aliases": [
   "Cree"
  ],
  "division": "ADLT Lighting Group",
  "parentCompany": "CLNA Holdings, LLC (Advanced Lighting Technologies / ADLT group)",
  "sourceUrl": "https://www.ewweb.com/news/mergers-acquisitions/article/21273641/ideal-sells-cree-lighting-division-to-advanced-lighting-technologies-clna-holdings",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Belden",
  "aliases": [
   "Belden Inc."
  ],
  "parentCompany": "Belden Inc.",
  "sourceUrl": "https://investor.belden.com/overview/default.aspx",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/b/belden.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "CommScope",
  "aliases": [
   "CommScope Holding Company, Inc."
  ],
  "division": "Amphenol Communications Solutions segment (former CommScope Connectivity and Cable Solutions / CCS business)",
  "parentCompany": "Amphenol Corporation",
  "sourceUrl": "https://www.commscope.com/about-us/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Corning",
  "aliases": [
   "Corning Incorporated"
  ],
  "parentCompany": "Corning Incorporated",
  "sourceUrl": "https://www.corning.com/",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/c/corning.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Cisco",
  "aliases": [
   "Cisco Systems, Inc."
  ],
  "parentCompany": "Cisco Systems, Inc.",
  "sourceUrl": "https://www.nasdaq.com/market-activity/stocks/csco",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Axis",
  "aliases": [
   "Axis Communications",
   "Axis Communications AB"
  ],
  "parentCompany": "Canon Inc.",
  "sourceUrl": "https://global.canon/en/news/2018/20181022.html",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/a/axis.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Hanwha Vision",
  "aliases": [
   "Hanwha Techwin",
   "Samsung Techwin"
  ],
  "division": "Hanwha Group — Aerospace & Defense, Mechatronics segment",
  "parentCompany": "Hanwha Group",
  "sourceUrl": "https://www.hanwha.com/companies/hanwha-vision.do",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/h/hanwha.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Honeywell Home",
  "parentCompany": "Resideo Technologies, Inc.",
  "sourceUrl": "https://www.prnewswire.com/news-releases/resideo-introduces-honeywell-home-x2s-smart-thermostat-at-ces-2025-302343040.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Honeywell Howard Leight",
  "aliases": [
   "Howard Leight"
  ],
  "parentCompany": "Protective Industrial Products, Inc. (a portfolio company of Odyssey Investment Partners)",
  "sourceUrl": "https://us.pipglobal.com/en/about-us/news-and-events/?type=pr&nID=264",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Omron",
  "aliases": [
   "OMRON Corporation"
  ],
  "division": "OMRON Industrial Automation",
  "parentCompany": "OMRON Corporation",
  "sourceUrl": "https://industrial.omron.eu/en/company-info",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Phoenix Contact",
  "parentCompany": "Phoenix Contact GmbH & Co. KG",
  "sourceUrl": "https://www.phoenixcontact.com/en-us/company/phoenix-contact-group",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "WAGO",
  "aliases": [
   "WAGO Corporation",
   "WAGO Kontakttechnik GmbH & Co. KG"
  ],
  "parentCompany": "WAGO GmbH & Co. KG",
  "sourceUrl": "https://www.wago.com/ca-en/company",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/w/wago-corporation.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Mean Well",
  "aliases": [
   "MEAN WELL Enterprises Co., Ltd."
  ],
  "parentCompany": "MEAN WELL Enterprises Co., Ltd.",
  "sourceUrl": "https://www.meanwell.com/aboutstory.aspx",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Intermatic",
  "aliases": [
   "Intermatic Incorporated",
   "Intermatic, LLC"
  ],
  "parentCompany": "MPE Partners",
  "sourceUrl": "https://www.mpepartners.com/portfolio/intermatic/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Generac",
  "aliases": [
   "Generac Holdings Inc.",
   "Generac Power Systems, Inc."
  ],
  "parentCompany": "Generac Holdings Inc.",
  "sourceUrl": "https://investors.generac.com/faqs",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Hoffman",
  "aliases": [
   "nVent HOFFMAN"
  ],
  "division": "nVent HOFFMAN (enclosures)",
  "parentCompany": "nVent",
  "sourceUrl": "https://www.nvent.com/en-us/our-brands/HOFFMAN",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/n/nvent.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "nVent ERICO",
  "aliases": [
   "ERICO"
  ],
  "division": "nVent ERICO (grounding, bonding and lightning protection)",
  "parentCompany": "nVent",
  "sourceUrl": "https://www.nvent.com/en-us/erico/solutions/grounding-earthing-bonding",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/n/nvent.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Appleton",
  "aliases": [
   "Appleton Group",
   "Appleton Grp"
  ],
  "division": "Appleton Group",
  "parentCompany": "Emerson Electric Co.",
  "sourceUrl": "https://www.emerson.com/en-us/automation/appleton",
  "wescoBrandUrl": "https://www.wesco.com/us/en/brands/e/emerson.html",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Carlon",
  "aliases": [
   "Carlon (Thomas & Betts)"
  ],
  "division": "ABB Electrification (Thomas & Betts)",
  "parentCompany": "ABB",
  "sourceUrl": "https://electrification.us.abb.com/products/boxes-commercial-fittings/carlon-pvc-elbows-fittings",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "Wheatland",
  "aliases": [
   "Wheatland Tube"
  ],
  "division": "Wheatland Tube, a division of Zekelman Industries",
  "parentCompany": "Zekelman Industries",
  "sourceUrl": "https://www.zekelman.com/our-companies/wheatland-tube/",
  "verifiedAt": "2026-06-11"
 },
 {
  "brand": "AFC Cable Systems",
  "aliases": [
   "AFC Cable Systems, Inc.",
   "AFC"
  ],
  "parentCompany": "Atkore",
  "sourceUrl": "https://www.atkore.com/about-us/brands/afc-cable-systems",
  "verifiedAt": "2026-06-11"
 }
];
