import type { VerifiedCrossEntry } from "@/lib/catalog/verified-crosses";

/**
 * Source-backed cross-reference pairs (verified-data research workflow, 2026-06-11).
 * Every pair cites the official cross-reference tool, datasheet, or published
 * cross table that states it — link-verified at research time. Qualifiers from
 * the source (UL-classification limits, coil/aux differences) are preserved in
 * notes and MUST be surfaced with the recommendation.
 * GENERATED by scripts/ingest-research-results.mjs — do not add pairs without
 * a citable source.
 */
export const VERIFIED_CROSS_ENTRIES: VerifiedCrossEntry[] = [
 {
  "aBrand": "Square D",
  "aMpn": "QO115",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "CHQ115",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://rexel-cdn.com/products/breakers-classifedtype.pdf?i=7969BAC6-13FD-414A-B6C0-B48C72385185",
  "notes": "Valid only per the UL classification terms: CHQ is a 3/4-in classified breaker for replacement use in Square D QO loadcenters; 120/240 VAC, 10 kAIC; clamshell pack CHQ115CS also listed. Not a same-brand listed equivalent.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "QO120",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "CHQ120",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://rexel-cdn.com/products/breakers-classifedtype.pdf?i=7969BAC6-13FD-414A-B6C0-B48C72385185",
  "notes": "UL Classified for replacement use in Square D QO loadcenters only; 120/240 VAC, 10 kAIC; clamshell pack CHQ120CS also listed.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "QO230",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "CHQ230",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://rexel-cdn.com/products/breakers-classifedtype.pdf?i=7969BAC6-13FD-414A-B6C0-B48C72385185",
  "notes": "UL Classified for replacement use in Square D QO loadcenters only; 2-pole 120/240 VAC, 10 kAIC; clamshell pack CHQ230CS also listed.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "HOM120CP",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "CL120",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://rexel-cdn.com/products/breakers-classifedtype.pdf?i=7969BAC6-13FD-414A-B6C0-B48C72385185",
  "notes": "UL Classified 1-in replacement breaker; valid only in the listed manufacturers' loadcenters. Chart lists base catalog HOM120; our HOM120CP is Schneider's clamshell-pack catalog number for the same Homeline 20 A 1-pole 120/240 VAC plug-in breaker (per se.com product page) — verify packaging-suffix mapping in catalog data.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "HOM230CP",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "CL230",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://rexel-cdn.com/products/breakers-classifedtype.pdf?i=7969BAC6-13FD-414A-B6C0-B48C72385185",
  "notes": "UL Classified 1-in replacement breaker for Square D Homeline (and listed Crouse-Hinds/Siemens/Murray/T&B) loadcenters; 2-pole 120/240 VAC, 10 kAIC; clamshell pack CL230CS also listed. Chart lists base catalog HOM230; HOM230CP is the clamshell-pack number of the same 30 A 2-pole Homeline breaker — verify suffix mapping.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "QO115",
  "bBrand": "Siemens",
  "bMpn": "D115",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://media.distributordatasolutions.com/siemenssi/2020q1/2bcea7e2ac2999ce0b76302a4f39f6e0065f1c7e.pdf",
  "notes": "Type QD is UL Classified for use in place of Square D Type QO breakers only in the specific Square D UL-listed panelboards enumerated in the bulletin's compatibility list; 'Do not use in series rated systems with those panelboards'; not series rated with Square D equipment; 10 kAIC max, 120/240 VAC.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "QO120",
  "bBrand": "Siemens",
  "bMpn": "D120",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://media.distributordatasolutions.com/siemenssi/2020q1/2bcea7e2ac2999ce0b76302a4f39f6e0065f1c7e.pdf",
  "notes": "UL Classified only for the Square D listed panelboards on the bulletin's compatibility list; do not use in series-rated systems; 10 kAIC max; 15/20 A 1-pole QD breakers are SWD rated.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "QO230",
  "bBrand": "Siemens",
  "bMpn": "D230",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://media.distributordatasolutions.com/siemenssi/2020q1/2bcea7e2ac2999ce0b76302a4f39f6e0065f1c7e.pdf",
  "notes": "UL Classified only for the Square D listed panelboards on the bulletin's compatibility list; do not use in series-rated systems; 2-pole 120/240 VAC, 10 kAIC max.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Eaton",
  "aMpn": "CH115",
  "bBrand": "Square D",
  "bMpn": "QO115",
  "relation": "functional-substitute",
  "sourceKind": "industry-table",
  "sourceUrl": "https://rexel-cdn.com/Products/957F33D7-074C-47F8-BD3F-F61946CF4628/957F33D7-074C-47F8-BD3F-F61946CF4628.pdf",
  "notes": "Source explicitly states Eaton breakers are NOT direct replacements for Square D part numbers — 'comparable alternative for reference only'; breaker brand typically must match panel brand to keep agency certification. Treat as catalog-comparison cross, not an installation-approved replacement.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Eaton",
  "aMpn": "BR120",
  "bBrand": "Square D",
  "bMpn": "HOM120",
  "relation": "functional-substitute",
  "sourceKind": "industry-table",
  "sourceUrl": "https://rexel-cdn.com/Products/957F33D7-074C-47F8-BD3F-F61946CF4628/957F33D7-074C-47F8-BD3F-F61946CF4628.pdf",
  "notes": "Same source disclaimer: not a direct replacement, comparable alternative for reference only; panel brand must match breaker brand to preserve certification. HOM120 is the standard-pack number of our HOM120CP clamshell catalog item.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Allen-Bradley",
  "aMpn": "100-C09D10",
  "bBrand": "ABB",
  "bMpn": "AF09-30-10-13",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://empower.abb.com/ecatalog/ec/EN_NA/competitors/search/ajax?competitorName=&competitorCode=100-C09D10",
  "notes": "ABB flags this as 'Close Match', not 'Exact Match' — AF09 uses a 100-250V AC/DC electronic coil vs the 100-C09D10 fixed AC coil; verify coil control scheme and accessory compatibility. Human-facing tool: https://empower.abb.com/ecatalog/ec/EN_NA/competitors/sub-detail/",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Schneider Electric",
  "aMpn": "LC1D09G7",
  "bBrand": "ABB",
  "bMpn": "AF09-30-10-13",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://empower.abb.com/ecatalog/ec/EN_NA/competitors/search/ajax?competitorName=&competitorCode=LC1D09G7",
  "notes": "Both sides of this pair are in our catalog. ABB lists the competitor code as 'LC1-D09G7' (legacy hyphenated form of LC1D09G7, 120V coil). 'Close Match', not exact: AF09 has a wide-range 100-250V AC/DC coil vs the fixed 120V AC coil of the G7.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Schneider Electric",
  "aMpn": "LC1D18G7",
  "bBrand": "ABB",
  "bMpn": "AF16-30-10-13",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://empower.abb.com/ecatalog/ec/EN_NA/competitors/search/ajax?competitorName=&competitorCode=LC1D18G7",
  "notes": "ABB's own qualifier: add one CA4-01 auxiliary contact if required — LC1D18 ships with 1NO+1NC built-in aux while AF16-30-10 has only 1NO, so the NC function needs the CA4-01 add-on. Match type 'Close Match'.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Siemens",
  "aMpn": "3RT2026-1AK60",
  "bBrand": "ABB",
  "bMpn": "AF26N1-30-00-13",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://empower.abb.com/ecatalog/ec/EN_NA/competitors/search/ajax?competitorName=&competitorCode=3RT2026-1AK60",
  "notes": "ABB marks this 'Exact Match'. ABB comment 'SIZE 0 ONLY GOES TO 18 AMPS' explains why the NEMA Size 1 AF26N1 (not a smaller frame) is the cross for this 25 A AC-3 contactor. AF26N1 has no built-in aux (-00); the 3RT2026-1AK60 also has none built into the base S0 device.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Allen-Bradley",
  "aMpn": "100-C23D10",
  "bBrand": "ABB",
  "bMpn": "AF30-30-00-13",
  "relation": "functional-substitute",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://empower.abb.com/ecatalog/ec/EN_NA/competitors/search/ajax?competitorName=&competitorCode=100-C23D10",
  "notes": "'Close Match': the suggested AF30-30-00 has no built-in auxiliary contact while the 100-C23D10 includes 1 NO aux — an ABB front aux block must be added to replicate the aux function. AF30 coil is 100-250V AC/DC vs the fixed 120V AC coil of the D10 suffix part.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "8910DPA32V02",
  "bBrand": "Eaton (Cutler-Hammer)",
  "bMpn": "C25DND230A",
  "relation": "equivalent",
  "sourceKind": "industry-table",
  "sourceUrl": "https://s3.amazonaws.com/s3.supplyhouse.com/product_files/45FG20AG-cross%20reference.pdf",
  "notes": "Row also lists Zettler XMC0-323AFBBD, Siemens (Furnas) 42BF15AF and GE CR453AC2AAA. 30 A 2-pole DP contactor, 110/120V coil (Square D V02 = Eaton coil code A). Verify mounting plate and quick-connect terminal layout when swapping DP contactors. Document hosted by distributor SupplyHouse.com.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "8910DPA32V02",
  "bBrand": "Siemens (Furnas)",
  "bMpn": "42BF15AF",
  "relation": "equivalent",
  "sourceKind": "industry-table",
  "sourceUrl": "https://s3.amazonaws.com/s3.supplyhouse.com/product_files/45FG20AG-cross%20reference.pdf",
  "notes": "42BF15AF is the legacy Furnas 30 A 2-pole DP contactor with 110/120V coil (F coil code), now a Siemens catalog number. Same row also crosses to GE CR453AC2AAA and Cutler-Hammer C25DND230A. Verify footprint/terminals before substitution.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Square D",
  "aMpn": "8910DPA32V02",
  "bBrand": "GE",
  "bMpn": "CR453AC2AAA",
  "relation": "equivalent",
  "sourceKind": "industry-table",
  "sourceUrl": "https://s3.amazonaws.com/s3.supplyhouse.com/product_files/45FG20AG-cross%20reference.pdf",
  "notes": "30 A 2-pole definite-purpose contactor, 110/120V coil on both sides of the cross. GE CR453 line has since transitioned to ABB ownership; check current availability. Verify mounting and termination.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hubbell",
  "aMpn": "HBL5262",
  "bBrand": "Cooper (Arrow Hart)",
  "bMpn": "AH5262B",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "Arrow Hart is now an Eaton brand. Guide is dated 2013 and matches competitor catalog numbers to the preferred Hubbell item for bin re-stocking; verify current color/packaging suffixes.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hubbell",
  "aMpn": "HBL5262",
  "bBrand": "Pass & Seymour",
  "bMpn": "5262-A",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "PDF-to-text extraction overlaps the Leviton and P&S columns in this row (both render as '5262A'); the string matches P&S's 5262-A numbering scheme exactly, but confirm column attribution against the printed page before publishing.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hubbell",
  "aMpn": "HBL5362W",
  "bBrand": "Cooper (Arrow Hart)",
  "bMpn": "AH5362W",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "Arrow Hart is now an Eaton brand. 2013 edition; confirm current part status.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hubbell",
  "aMpn": "HBL5362W",
  "bBrand": "Pass & Seymour",
  "bMpn": "PS5362-W",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "PDF table extraction places PS5362W on a continuation line of the white row; verify against the printed page. P&S PS5362-W is a current Legrand/Pass & Seymour catalog number.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Pass & Seymour",
  "aMpn": "CR20W",
  "bBrand": "Hubbell",
  "bMpn": "CR20WHI",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "Row reads: Hubbell CR20WHI | Arrow Hart CR20W | Cooper CR20W | Leviton CR020W / CR20W | P&S CR20W. Hubbell uses 'WHI' as its white suffix on this series.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Pass & Seymour",
  "aMpn": "CR20W",
  "bBrand": "Leviton",
  "bMpn": "CR020-W",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "Leviton column prints two values (CR020W / CR20W); CR020-W is Leviton's catalog number for its 20A commercial spec-grade duplex.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Pass & Seymour",
  "aMpn": "CR20W",
  "bBrand": "Cooper (Arrow Hart)",
  "bMpn": "CR20W",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://hubbellcdn.com/ohwassets/HCI/WiringDevice/literature/BIN_Stock_Guide_2013.pdf",
  "notes": "Catalog numbers are identical strings across P&S and Cooper/Arrow Hart for this commercial series (industry-common CR20 numbering); brand on the box differs. Arrow Hart is now Eaton.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Keystone",
  "aMpn": "KTEB-232-UV-IS-N-P",
  "bBrand": "Philips Advance",
  "bMpn": "IOP-2P32-SC",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://pimmedia.winsupplyinc.com/pim/CUT/122017/KEYSTONE-BALLAST_KTEB-275-UV-TP-PIC_89094900188_CUT.pdf",
  "notes": "Keystone document states it 'does not warrant or guarantee the accuracy of this cross reference guide' and to contact Keystone for proper ballast selection; document is Keystone-authored, hosted on distributor (Winsupply) PIM.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Keystone",
  "aMpn": "KTEB-232-UV-IS-N-P",
  "bBrand": "Universal (ULT/Magnetek)",
  "bMpn": "B232IUNVHE-A",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://pimmedia.winsupplyinc.com/pim/CUT/122017/KEYSTONE-BALLAST_KTEB-275-UV-TP-PIC_89094900188_CUT.pdf",
  "notes": "Same Keystone accuracy disclaimer applies; confirm physical case/mounting before substitution.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Keystone",
  "aMpn": "KTEB-232-UV-IS-N-P",
  "bBrand": "GE",
  "bMpn": "GE232MAX-N/ULTRA",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://pimmedia.winsupplyinc.com/pim/CUT/122017/KEYSTONE-BALLAST_KTEB-275-UV-TP-PIC_89094900188_CUT.pdf",
  "notes": "Same Keystone accuracy disclaimer applies.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Keystone",
  "aMpn": "KTEB-232-UV-IS-N-P",
  "bBrand": "Sylvania",
  "bMpn": "QHE2X32T8/UNVISN-SC",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://pimmedia.winsupplyinc.com/pim/CUT/122017/KEYSTONE-BALLAST_KTEB-275-UV-TP-PIC_89094900188_CUT.pdf",
  "notes": "This is the verified Sylvania QHE cross requested ('QHE only if sourced'); same Keystone accuracy disclaimer applies.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Philips Advance",
  "aMpn": "ICN-2P32-N",
  "bBrand": "Osram Sylvania",
  "bMpn": "QTP2X32T8/UNV-SC",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://www.assets.signify.com/is/content/Signify/Assets/advance/20190931-cross-reference-guide-osram-motorola.pdf",
  "notes": "Guide brands the competitor line 'Osram-Motorola'; QTP2X32T8/UNV-SC is a Sylvania Quicktronic model. Signify disclaims warranty as to accuracy/completeness of the guide.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Philips Advance",
  "aMpn": "ICN-4P32-N",
  "bBrand": "Osram Sylvania",
  "bMpn": "QTP4X32T8/UNV-SC",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://www.assets.signify.com/is/content/Signify/Assets/advance/20190931-cross-reference-guide-osram-motorola.pdf",
  "notes": "Some 4-lamp variants in the same guide carry the note 'Dimensions differ significantly' (e.g. QT4X32T8/120ISN-K-G4); the QTP4X32T8/UNV-SC row has no caveat, but check housing dimensions when retrofitting.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Philips Advance",
  "aMpn": "ICF-2S26-H1-LD",
  "bBrand": "GE",
  "bMpn": "GEC226-MVPS-SE",
  "relation": "equivalent",
  "sourceKind": "manufacturer-cross",
  "sourceUrl": "https://www.assets.signify.com/is/content/Signify/Assets/advance/20190931-cross-reference-guide-ge.pdf",
  "notes": "Cross runs GE-to-Advance (ICF-2S26-H1-LD replaces GEC226-MVPS-SE); Signify disclaims warranty as to accuracy/completeness of the guide.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hatch",
  "aMpn": "LC40-1050Z-UNV-W",
  "bBrand": "Delta Electronics",
  "bMpn": "USCI-040105FA",
  "relation": "functional-substitute",
  "sourceKind": "distributor-cross",
  "sourceUrl": "https://forum.digikey.com/t/alternative-for-obsolete-led-driver-usci-040105fa/43073",
  "notes": "Not a 1:1 equivalent: input range differs (120-277VAC vs 108-305VAC), output voltage window differs (12-36V vs 26-38V), and dimensions/temperature ratings differ - DigiKey says to verify against the datasheet before use.",
  "verifiedAt": "2026-06-11"
 },
 {
  "aBrand": "Hatch",
  "aMpn": "LC40-1050Z-UNV-W",
  "bBrand": "Mean Well",
  "bMpn": "GSC40B-1050",
  "relation": "functional-substitute",
  "sourceKind": "distributor-cross",
  "sourceUrl": "https://forum.digikey.com/t/alternative-for-obsolete-led-driver-gsc40b-1050/43425",
  "notes": "Qualifiers from source: Mean Well accepts 90-277VAC vs Hatch 120-277VAC; output 19-38V vs 12-36V; Mean Well uses a barrel plug vs Hatch wire leads - verify wiring and LED load voltage.",
  "verifiedAt": "2026-06-11"
 }
];
